add from_get_instance_proc_addr to Entry
Ralith/openxrs pull request #117
Opened 2022-06-09 17:12 UTC by CodeWitchBella

Implements #116 

I did test it in my project and it works. At least it does for `.fp().create_instance`

I am new to rust, so I apologize if this is wrong

2022-06-20 16:36 UTC, Ralith requested changes
Looks reasonable overall.

2022-07-24 16:18 UTC, CodeWitchBella commented on openxr/src/entry.rs
> +    unsafe fn get_instance_proc_addr_static(
Makes sense, extracted. I apologize for taking so long to change this 😅

2022-07-24 16:33 UTC, Ralith commented on openxr/src/entry.rs
> +    unsafe fn get_instance_proc_addr_static(
No worries!

2022-07-24 16:33 UTC, Ralith approved these changes

2022-07-24 16:36 UTC, merged