Add OpenGL ES support
Ralith/openxrs pull request #128
Opened 2022-12-24 14:57 UTC by zarik5

Tested with https://github.com/alvr-org/ALVR/tree/openxr-client/alvr/client_openxr .

2022-12-24 19:48 UTC, Ralith commented
Thanks! Can you justify the decision to select GL ES automatically iff targeting Android? Does Android not support regular OpenGL? Does this require the user to adjust the extensions they enable depending on whether building for Android?

2022-12-25 11:51 UTC, zarik5 commented
OpenGL is for desktop and OpenGL ES is for embedded, they are mutually exclusive. Furthermore, the OpenXR documentation says that the `XR_KHR_opengl_es_enable` extension is tailored for android at the moment. You can use an abstraction layer over the two APIs (like the glow Rust crate) but EGL code is still platform-specific.

2022-12-26 18:37 UTC, Ralith commented
Then there's no point trying to pretend OpenGL and OpenGL ES are the same thing. Let's expose a separate `Graphics` impl instead.

2022-12-26 21:14 UTC, zarik5 commented
> Then there's no point trying to pretend OpenGL and OpenGL ES are the same thing. Let's expose a separate Graphics impl instead.

The reason behind this is, as I said, they are mutually exclusive, and also they can share some of the wrapper code, but that's a fair point. I will make a separate Graphics implementation.

2022-12-28 03:07 UTC, Ralith commented
> they are mutually exclusive

I don't think this is actually true. For example, [Mesa's implementation](https://docs.mesa3d.org/opengles.html) should work just fine on desktop Linux, and targeting it might be desirable for testing or portability.

2022-12-28 10:59 UTC, zarik5 commented
> I don't think this is actually true

Yeah, they are both open standards and in particular OpenGL ES is preferred as a common denominator and wrapper layer since it is mostly a subset of OpenGL (see Google ANGLE). And Mesa being opensource can do what it wants. In any case the OpenXR documentation says `XR_KHR_opengl_es_enable` is Android only. We can relax this restriction once there is really support for other non-Android platforms for this extension.

2022-12-28 19:00 UTC, Ralith requested changes
Let's drop the `#[cfg(not(target_os = "android")]` qualifiers this introduces, since they make this a breaking change and don't serve much purpose. Apps should already be checking extension support, and the loader will return an error on attempting to use an unsupported extension anyway.

2022-12-28 19:11 UTC, zarik5 commented on openxr/src/graphics/opengles.rs
> +pub enum OpenGles {}
I was conflicted on this. The proper capitalization should have been OpenGLES but the compiler warns struct identifiers with 3 or more consecutive capitalized letters. If we consider "OpenGL ES" as the original name (with a space) then `OpenGlEs` is the result after casing conversion but that looks wonky. another alternative is to keep `OpenGLES` and disable the casing warning.

2022-12-28 19:22 UTC, Ralith commented on openxr/src/graphics/opengles.rs
> +pub enum OpenGles {}
The convention is for acronyms to be treated as words, i.e. only the first letter capitalized. This helps keep type naming style distinct from constant naming style.

2022-12-28 19:57 UTC, zarik5 commented on openxr/src/graphics/opengles.rs
> +pub enum OpenGles {}
My only nit is that it looks wonky. Anyway that's not that important. Rebased.

2022-12-29 01:28 UTC, Ralith approved these changes
Thanks!

2022-12-29 01:29 UTC, merged