Add back khr_vulkan_enable support
Ralith/openxrs pull request #85
Opened 2021-07-05 14:01 UTC by zarik5

As proposed in #84.

The code is mostly copy-pasted from the tag v0.13.1

2021-07-05 17:34 UTC, Ralith requested changes
Wow, that's way smaller a change than I expected. Awesome!

Let's name the legacy methods a little more distinctively to avoid confusion with the new ones.

2021-07-05 17:34 UTC, Ralith commented on openxr/src/instance.rs
> +    pub fn vulkan_instance_extensions(&self, system: SystemId) -> Result<String> {
```suggestion
    pub fn vulkan_legacy_instance_extensions(&self, system: SystemId) -> Result<String> {
```

2021-07-05 17:34 UTC, Ralith commented on openxr/src/instance.rs
> +    pub fn vulkan_device_extensions(&self, system: SystemId) -> Result<String> {
```suggestion
    pub fn vulkan_legacy_device_extensions(&self, system: SystemId) -> Result<String> {
```

2021-07-05 17:34 UTC, Ralith commented on openxr/src/instance.rs
> +    /// **Note:** This method requires `khr_vulkan_enable` extension. Applications should use
```suggestion
    /// **Note:** This method requires the `khr_vulkan_enable` extension. Applications should use
```

2021-07-05 17:34 UTC, Ralith commented on openxr/src/instance.rs
> +    /// **Note:** This method requires `khr_vulkan_enable` extension. Applications should use
```suggestion
    /// **Note:** This method requires the `khr_vulkan_enable` extension. Applications should use
```

2021-07-07 10:32 UTC, zarik5 commented
The PR should be ready for merging.

2021-07-12 03:02 UTC, Ralith approved these changes
Thanks!

2021-07-12 03:11 UTC, merged